- name: Configure port forwarding on Mikrotik routers
  hosts: mikrotik_routers
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    forwarding_table:
      '10.0.0.1': '10.0.0.45'
      '10.0.1.1': '10.0.1.55'
  tasks:
    - name: Forward ports for email traffic
      community.routeros.api_modify:
        hostname: "{{ inventory_hostname }}"
        password: "Saske912!"
        username: "admin"
        path: ip firewall nat
        data:
        - action: dst-nat
          chain: dstnat
          protocol: tcp
          dst_port: "465,25,110,995,993,587"
          in_interface: "{{ 'ether1' if inventory_hostname == 'mikrotik1' else 'ether2' }}"
          to_addresses: "{{ forwarding_table[inventory_hostname] }}"
          state: present
